changelog:
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Docs & Tooling
      labels:
        - docs
        - tooling
    - title: Other
      labels:
        - "*"
